from pathlib import Path

try:
    Import("env")  # type: ignore[name-defined]
    PROJECT_DIR = Path(env["PROJECT_DIR"])
except NameError:
    PROJECT_DIR = Path(__file__).resolve().parents[1]

ASSETS_DIR = PROJECT_DIR / "components" / "web" / "assets"
GENERATED_DIR = PROJECT_DIR / "components" / "web" / "generated"

ASSETS = [
    ("index.html", "web_asset_index_html"),
    ("app.js", "web_asset_app_js"),
    ("styles.css", "web_asset_styles_css"),
]


def format_byte_array(data: bytes) -> str:
    if not data:
        return "    0x00"

    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        line = ", ".join(f"0x{value:02x}" for value in chunk)
        lines.append(f"    {line}")
    return ",\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def main() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)

    header_lines = [
        "/* Auto-generated by tools/embed_web_assets.py. Do not edit directly. */",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]

    source_lines = [
        "/* Auto-generated by tools/embed_web_assets.py. Do not edit directly. */",
        '#include "web_assets.h"',
        "",
    ]

    for asset_name, symbol_name in ASSETS:
        asset_path = ASSETS_DIR / asset_name
        data = asset_path.read_bytes()

        header_lines.append(f"extern const uint8_t {symbol_name}[];")
        header_lines.append(f"extern const size_t {symbol_name}_len;")
        header_lines.append("")

        source_lines.append(f"const uint8_t {symbol_name}[] = {{")
        source_lines.append(format_byte_array(data))
        source_lines.append("};")
        source_lines.append(f"const size_t {symbol_name}_len = sizeof({symbol_name});")
        source_lines.append("")

    header_content = "\n".join(header_lines) + "\n"
    source_content = "\n".join(source_lines) + "\n"

    write_if_changed(GENERATED_DIR / "web_assets.h", header_content)
    write_if_changed(GENERATED_DIR / "web_assets.c", source_content)


main()
